spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ittraining?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
